spring:
  application:
    name: michelle

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 41000

githubconfig:
  login: ${GITHUB_LOGIN}
  url: ${GITHUB_URL}
  token: ${GITHUB_OAUTH}
