spring:
  application:
    name: michelle

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 41000

logging:
  hook: ${MATTERMOST_LOG_WEBHOOK}
  payload: "{\"username\":\"Logger\",\"icon_url\":\"https://www.turing.sintergica.ai/static/favicon.png\",\"text\": \"$MESSAGE\"}"

githubconfig:
  login: ${GITHUB_LOGIN}
  url: https://api.github.com
  token: ${GITHUB_OAUTH}

digitalocean:
  token: ${DO_TOKEN}
  sshKeyId: ${SSH_KEY_ID}
  sshKeyName: ${SSH_KEY_NAME}
  sshKeyFingerprint: ${SSH_KEY_FINGERPRINT}

general:
  webhookUrl: ":80/tokenhook/"
  httpRequestTimeout: 500
  antonPort: 42000

