name: michelle

services:
  - name: michelle
    image:
      registry_type: GHCR
      registry: sintergicaai
      repository: michelle
      tag: ${IMAGE_TAG}
      instance_size_slug: apps-s-1vcpu-1gb-fixed
      instance_count: 1
      registry_credentials: ${GH_CREDENTIALS}
      autoscaling:
        min_instance_count: 1
        max_instance_count: 1
    http_port: ${HTTP_PORT}
    envs:
      - key: GITHUB_OAUTH
        value: ${GH_TOKEN}
        type: SECRET
        scope: RUN_TIME

      - key: GITHUB_LOGIN
        value: SintergicaAI
        type: GENERAL
        scope: RUN_TIME

      - key: GITHUB_URL
        value: https://api.github.com
        type: GENERAL
        scope: RUN_TIME

      - key: DB_URL
        value: ${DB_URL}
        type: SECRET
        scope: RUN_TIME

      - key: DB_USERNAME
        value: ${DB_USERNAME}
        type: SECRET
        scope: RUN_TIME

      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
        type: SECRET
        scope: RUN_TIME

      - key: SSH_KEY_FINGERPRINT
        value: ${SS_KEY_FINGERPRINT}
        type: SECRET
        scope: RUN_TIME

      - key: SSH_KEY_ID
        value: ${SSH_KEY_ID}
        type: SECRET
        scope: RUN_TIME

      - key: SSH_KEY_NAME
        value: mainKey
        type: GENERAL
        scope: RUN_TIME

      - key: MATTERMOST_LOG_WEBHOOK
        value: ${MATTERMOST_WEBHOOK}
        type: SECRET
        scope: RUN_TIME
