openapi: 3.0.0
info:
  title: Michelle
  description: Michelle es un servicio que administra las operaciones para la organización de SintergicaAI
  version: 0.1.3
  contact:
    name: Edson Manuel Carballo Vera
    email: edson.vera@sintergica.ai
servers:
  - url: 'https://michelle-at5k7.ondigitalocean.app/'
    description: Servidor de produccion

paths:
  /package:
    $ref: "package.yaml"
  /repository:
    $ref: "repository.yaml"
  /repository/{name}:
    $ref: "repository.name.yaml"
  /server:
    $ref: "server.yaml"
  /server/{serverName}:
    summary: Endpoint para administrar un servidor
    description: Endpoint para administrar la informacion de un servidor identificado por su nombre
    delete:
      summary: Elimina un servidor
      description: Elimina un servidor identificado por su nombre
      tags:
        - Server
      security:
        - basicAuth: [ ]
      parameters:
        - name: serverName
          description: Nombre del servidor a eliminar
          in: path
          schema:
            type: string
            example: openwebui-droplet
          required: true
      responses:
        200:
          description: Se ha eliminado el servidor
        404:
          description: No se ha encontrado el servidor
        500:
          $ref: "components.yaml#/components/responses/500"

