openapi: 3.0.0
info:
  title: Michelle
  description: Michelle es un servicio que administra las operaciones para la organización de SintergicaAI
  version: 0.2.0
  contact:
    name: Edson Manuel Carballo Vera
    email: edson.vera@sintergica.ai
servers:
  - description: Servidor de producción
    url: https://michelle-hoyto.ondigitalocean.app/
paths:
  /package:
    $ref: "package.yaml"
  /repository:
    $ref: "repository.yaml"
  /repository/{name}:
    $ref: "repository.name.yaml"
  /server:
    $ref: "server.yaml"
  /server/{serverName}:
    summary: Endpoint para administrar un servidor
    description: Endpoint para administrar la informacion de un servidor identificado por su nombre
    delete:
      summary: Elimina un servidor
      description: Elimina un servidor identificado por su nombre
      tags:
        - Server
      parameters:
        - name: serverName
          description: Nombre del servidor a eliminar
          in: path
          schema:
            type: string
            example: openwebui-droplet
          required: true
        - $ref: "components.yaml#/components/parameters/password"
      responses:
        200:
          description: Se ha eliminado el servidor
        404:
          description: No se ha encontrado el servidor
        500:
          $ref: "components.yaml#/components/responses/500"
  /event/{channel}:
    summary: Endpoint para administrar eventos
    description: Endpoint para administrar eventos
    post:
      summary: Registra un evento y subscribete a el
      description: Registra un evento y subscribete a el
      tags:
        - Events
      parameters:
        - name: channel
          description: Nombre del evento o canal
          in: path
          schema:
            type: string
            example: logout
          required: true
        - $ref: "components.yaml#/components/parameters/password"
      requestBody:
        description: Endpoint del webhook para notificar evento. El resto de la dirección se obtendrá del la llamada
        content:
          text/plain:
            schema:
              type: string
              example: /user/logout
      responses:
        200:
          description: Se ha registrado la subscripción
    put:
      summary: Dispara un evento
      description: Dispara un evento previamente registrado
      tags:
        - Events
      parameters:
        - name: channel
          description: Nombre del evento o canal
          in: path
          schema:
            type: string
            example: logout
          required: true
        - $ref: "components.yaml#/components/parameters/password"
      responses:
        200:
          description: Se ha disparado el evento
        404:
          description: El evento no se encuentra registrado
