name: "🚀Deploy service"

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      external_port:
        type: number
        description: Puerto para exponer el servicio
        required: true
        default: 81
      internal_port:
        type: number
        description: Puerto interno donde corre el servicio
        required: false
        default: 8080
      deploy_digital_ocean:
        type: boolean
        description: Desplegar en Digital Ocean
        default: false

  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest
      external_port:
        type: number
        description: Puerto para exponer el servicio
        required: true
        default: 41000
      internal_port:
        type: number
        description: Puerto interno donde corre el servicio
        required: true
        default: 41000
      deploy_digital_ocean:
        type: boolean
        description: Desplegar en Digital Ocean
        default: false

jobs:
  deploy_on_digital_ocean:
    if: ${{ fromJSON(inputs.deploy_digital_ocean) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy app
        uses: digitalocean/app_action/deploy@v2
        env:
          GH_TOKEN: ${{ secrets.ANTON_TOKEN }}
          GH_CREDENTIALS: 'GTWALOM:${{ secrets.ANTON_TOKEN }}'
          HTTP_PORT: ${{ inputs.external_port }}
          IMAGE_TAG: ${{ inputs.tag }}

        with:
          token: ${{ secrets.DO_TOKEN }}
          project_id: c95d7e2e-0ab6-4c15-99a3-e349470f3d4f
